name: Build and Deploy Documentation

on:
  push:
    branches: [ main, master ]
    paths-ignore:
      - '**.md'
      - 'docs/**'
    # Only trigger on commits with "docs-update" in the message
    # This is handled by the conditional check in the build job

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Need full history to check commit messages
    
    - name: Check commit message for docs-update
      id: check-commit
      run: |
        if git log --oneline -1 | grep -q "docs-update"; then
          echo "docs-update=true" >> $GITHUB_OUTPUT
        else
          echo "docs-update=false" >> $GITHUB_OUTPUT
        fi
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install sphinx sphinx-rtd-theme
    
    - name: Build documentation
      if: steps.check-commit.outputs.docs-update == 'true'
      run: |
        cd docs
        sphinx-build -b html . _build/html
      env:
        PYTHONPATH: ${{ github.workspace }}
    
    - name: Setup Pages
      if: steps.check-commit.outputs.docs-update == 'true'
      uses: actions/configure-pages@v4
    
    - name: Upload artifact
      if: steps.check-commit.outputs.docs-update == 'true'
      uses: actions/upload-pages-artifact@v3
      with:
        path: './docs/_build/html'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    if: needs.build.result == 'success'
    steps:
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
